FROM node:12-alpine

ENV PORT=3000

EXPOSE ${PORT}

RUN mkdir /home/node/app/ && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package*.json ./

USER node

RUN npm install && npm cache clean --force --loglevel=error

COPY --chown=node:node src ./app/

CMD [ "node", "src/app.js"]